package com.xworkz.exceptionhandlingAssignments;

public class DiffBtwUncheckedAndChecked {
	public static void main(String[] args) {
		System.out.println("DIFFERENCES BETWEEN UNCHECKED AND CHECKED EXCEPTION");
		System.out.println();
		System.out.println("||*Checked Exception*||");
		System.out.println("1. Checked exceptions occur at compile time.");
		System.out.println("2. The compiler checks a checked exception.");
		System.out.println("3. These types of exceptions can be handled at the time of compilation.");
		System.out.println("4. They are the sub-class of the exception class.");
		System.out.println("5. Here, the JVM needs the exception to catch and handle.");
		System.out.println("6. Examples : File Not Found Exception\r\n" + 
				"No Such Field Exception\r\n" + 
				"Interrupted Exception\r\n" + 
				"No Such Method Exception\r\n" + 
				"Class Not Found Exception");
		
		System.out.println();
		System.out.println();
	//	System.out.println();
		System.out.println("||*Unchecked Exception*||");
		System.out.println("1. Unchecked exceptions occur at runtime.");
		System.out.println("2. The compiler does not check these types of exceptions.");
		System.out.println("3. These types of exceptions cannot be a catch or handle at the time of compilation, because they get generated by the mistakes in the program.");
		System.out.println("4. They are runtime exceptions and hence are not a part of the Exception class.");
		System.out.println("5. Here, the JVM does not require the exception to catch and handle.");
		System.out.println("6. Examples : No Such Element Exception\r\n" + 
				"Undeclared Throwable Exception\r\n" + 
				"Empty Stack Exception\r\n" + 
				"Arithmetic Exception\r\n" + 
				"Null Pointer Exception\r\n" + 
				"Array Index Out of Bounds Exception\r\n" + 
				"Security Exception");
		
		
		
		
		
	}
}
